create table users (
    id serial unique,
    login text,
    updated_at timestamp,
    created_at timestamp
);

create table posts (
    id serial unique,
    user_id integer references users (id),
    title text,
    content text,
    created_at timestamp
);

create table comments (
    id serial unique,
    post_id integer references posts (id),
    title text,
    content text,
    created_at timestamp
);
